### PR TITLE
#15 Adding Attachments to emails

### LINKED ISSUE #15: Add attachments to email
Implement functionality for email composition to add attachments to email

Notes: Use Gmail API

Acceptance Criteria:

- [x] Can send an attachment with an email.

### PR DESCRIPTION
**Pull request by jameswatters1**
#15 Add Attachments to an email. This enables users to send attachments with their emails. Limits size at 25MB, gives alert and removes attachment if file exceeds size. GAPI limits what types of files can be sent (ex. no .js files). When testing this, check for attachments on real email client. Attachments do not show up in our inbox. 

closes #15

### CODE REVIEW

**Review by pbell97 — COMMENTED** [review]
Just tested a 30MB file and it said it sent, however I got an email back saying it failed. It seems it isn't validating the file size for me.

Also, is this based off an old branch? I'm not having any emails show up in the inbox page. Or am I doing something wrong?

**Comment by pbell97** [comment]
Ignore my previous comment. I was testing the old 'AddAttachments' branch.

**Review by pbell97 — APPROVED** [review]
Seems to work great after some quick tests.

**Review by D3ISM3 — APPROVED** [review]
Looks good boss.

**Review by nenntendo64 — APPROVED** [review]

**Pull request merged**
